/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dany.plo.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Dany Candra
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        frameProperties();
        // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTaskBar = new javax.swing.JPanel();
        jXCollapsiblePane1 = new org.jdesktop.swingx.JXCollapsiblePane();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        butonPengaturanQuota = new javax.swing.JButton();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panelUtama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCard = new javax.swing.JPanel();
        panelWellcome1 = new com.dany.plo.view.PanelWellcome();
        panelQuota = new com.dany.plo.view.PanelQuota();
        panelInstansi = new com.dany.plo.view.PanelInstansi();
        panelUser = new com.dany.plo.view.PanelUser();
        panelPejabat = new com.dany.plo.view.PanelPejabat();
        panelLokasi = new com.dany.plo.view.PanelLokasi();
        panelDus = new com.dany.plo.view.PanelDus();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTaskPane1.setTitle("Pengaturan");

        jButton1.setText("Penyimpanan");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jButton1);

        jButton3.setText("Pejabat");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jButton3);

        jButton8.setText("Instansi");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jButton8);

        jButton4.setText("Operator");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jButton4);

        butonPengaturanQuota.setText("Quota");
        butonPengaturanQuota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        butonPengaturanQuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPengaturanQuotaActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(butonPengaturanQuota);

        jXCollapsiblePane1.getContentPane().add(jXTaskPane1);

        jXTaskPane2.setTitle("Transaksi");

        jButton5.setText("Penerimaan Berkas");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXTaskPane2.getContentPane().add(jButton5);

        jButton6.setText("Pengembalian Berkas");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXTaskPane2.getContentPane().add(jButton6);

        jXTaskPane3.setTitle("Pencarian");

        jButton7.setText("Pencarian Berkas");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXTaskPane3.getContentPane().add(jButton7);

        jButton9.setText("Pencarian Dus");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXTaskPane3.getContentPane().add(jButton9);

        javax.swing.GroupLayout panelTaskBarLayout = new javax.swing.GroupLayout(panelTaskBar);
        panelTaskBar.setLayout(panelTaskBarLayout);
        panelTaskBarLayout.setHorizontalGroup(
            panelTaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXCollapsiblePane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXTaskPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(jXTaskPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTaskBarLayout.setVerticalGroup(
            panelTaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskBarLayout.createSequentialGroup()
                .addComponent(jXCollapsiblePane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 140, Short.MAX_VALUE))
        );

        panelUtama.setLayout(new java.awt.BorderLayout());

        panelCard.setLayout(new java.awt.CardLayout());
        panelCard.add(panelWellcome1, "card4");
        panelCard.add(panelQuota, "cardQuota");
        panelCard.add(panelInstansi, "cardInstansi");
        panelCard.add(panelUser, "cardUser");
        panelCard.add(panelPejabat, "cardPejabat");
        panelCard.add(panelLokasi, "cardLokasi");
        panelCard.add(panelDus, "cardDus");

        jScrollPane1.setViewportView(panelCard);

        panelUtama.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTaskBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTaskBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonPengaturanQuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPengaturanQuotaActionPerformed
        showPanel(panelQuota, "cardQuota");
        panelQuota.load();
    }//GEN-LAST:event_butonPengaturanQuotaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        showPanel(panelInstansi, "cardInstansi");
        panelInstansi.reload();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showPanel(panelLokasi, "cardLokasi");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showPanel(panelUser, "cardUser");
        panelUser.reload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        showPanel(panelPejabat, "cardPejabat");
        panelPejabat.reload();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonPengaturanQuota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXCollapsiblePane jXCollapsiblePane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private javax.swing.JPanel panelCard;
    private com.dany.plo.view.PanelDus panelDus;
    private com.dany.plo.view.PanelInstansi panelInstansi;
    private com.dany.plo.view.PanelLokasi panelLokasi;
    private com.dany.plo.view.PanelPejabat panelPejabat;
    private com.dany.plo.view.PanelQuota panelQuota;
    private javax.swing.JPanel panelTaskBar;
    private com.dany.plo.view.PanelUser panelUser;
    private javax.swing.JPanel panelUtama;
    private com.dany.plo.view.PanelWellcome panelWellcome1;
    // End of variables declaration//GEN-END:variables

    private void frameProperties() {
        this.setSize(1024, 720);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension framesize = this.getSize();
        if (framesize.height > screensize.height) {
            framesize.height = screensize.height;
        }
        if (framesize.width > screensize.width) {
            framesize.width = screensize.width;
        }
        this.setLocation((screensize.width - framesize.width) / 2, (screensize.height - framesize.height) / 2);
    }

    void showPanel(Component panel, String card) {
        if (panel.isVisible()) {
            return;
        }
        CardLayout layout = (CardLayout) panelCard.getLayout();
        layout.show(panelCard, card);
    }

}
