/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.dany.plo.view;

/**
 *
 * @author Dany Candra
 */
public class PanelWellcome extends javax.swing.JPanel {

    /**
     * Creates new form PanelWellcome
     */
    public PanelWellcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new com.dany.plo.view.resource.PanelImage();
        labelWhite1 = new com.dany.plo.view.resource.LabelWhite();
        labelWhite2 = new com.dany.plo.view.resource.LabelWhite();

        setLayout(new java.awt.BorderLayout());

        panelImage1.setImageBackground(new javax.swing.ImageIcon(getClass().getResource("/com/dany/plo/view/resource/unheard_sounds-wallpaper-1920x1080.jpg"))); // NOI18N

        labelWhite1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWhite1.setText("E-ARSIP CATUR");
        labelWhite1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWhite1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelWhite2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWhite2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dany/plo/view/resource/LOGO BANK JATENG 128.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWhite1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addComponent(labelWhite2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(labelWhite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(labelWhite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        add(panelImage1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dany.plo.view.resource.LabelWhite labelWhite1;
    private com.dany.plo.view.resource.LabelWhite labelWhite2;
    private com.dany.plo.view.resource.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
