/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dany.plo.view;

import com.dany.plo.controller.LantaiController;
import com.dany.plo.model.LantaiModel;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;

/**
 *
 * @author Dany Candra
 */
public class PanelLokasiLantai extends javax.swing.JPanel {
    
    private DynamicTableModel<LantaiModel> tableModel;
    private LantaiModel lantaiModel;
    private LantaiController lantaiController;

    /**
     * Creates new form PanelLantai
     */
    public PanelLokasiLantai() {
        lantaiModel = new LantaiModel();
        lantaiController=new LantaiController();
        tableModel = new DynamicTableModel<>(LantaiModel.class);
        
        initComponents();
        
        tableLantai.setDynamicModel(tableModel);
        lantaiController.setLantaiModel(lantaiModel);
    }

    public DynamicTableModel<LantaiModel> getTableModel() {
        return tableModel;
    }

    public JDynamicTable getTableLantai() {
        return tableLantai;
    }
    
    public void reload(){
        lantaiController.reload(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrud1 = new com.dany.plo.view.resource.PanelCrud();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLantai = new com.stripbandunk.jwidget.JDynamicTable();

        panelCrud1.addCrudListener(new com.dany.plo.view.resource.CrudListener() {
            public void hapus(com.dany.plo.view.resource.CrudEvent evt) {
                panelCrud1Hapus(evt);
            }
            public void ubah(com.dany.plo.view.resource.CrudEvent evt) {
                panelCrud1Ubah(evt);
            }
            public void segarkan(com.dany.plo.view.resource.CrudEvent evt) {
                panelCrud1Segarkan(evt);
            }
            public void tambah(com.dany.plo.view.resource.CrudEvent evt) {
                panelCrud1Tambah(evt);
            }
        });

        jScrollPane1.setViewportView(tableLantai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrud1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCrud1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelCrud1Hapus(com.dany.plo.view.resource.CrudEvent evt) {//GEN-FIRST:event_panelCrud1Hapus
        // TODO add your handling code here:
        lantaiController.crudDelete(this);
        reload();
    }//GEN-LAST:event_panelCrud1Hapus

    private void panelCrud1Tambah(com.dany.plo.view.resource.CrudEvent evt) {//GEN-FIRST:event_panelCrud1Tambah
        // TODO add your handling code here:
        lantaiController.crudInsret(this);
        reload();
    }//GEN-LAST:event_panelCrud1Tambah

    private void panelCrud1Segarkan(com.dany.plo.view.resource.CrudEvent evt) {//GEN-FIRST:event_panelCrud1Segarkan
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_panelCrud1Segarkan

    private void panelCrud1Ubah(com.dany.plo.view.resource.CrudEvent evt) {//GEN-FIRST:event_panelCrud1Ubah
        // TODO add your handling code here:
        lantaiController.crudUpdate(this);
        reload();
    }//GEN-LAST:event_panelCrud1Ubah


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.dany.plo.view.resource.PanelCrud panelCrud1;
    private com.stripbandunk.jwidget.JDynamicTable tableLantai;
    // End of variables declaration//GEN-END:variables
}
