/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dany.plo.view;

import com.dany.plo.controller.RakController;
import com.dany.plo.model.DusModel;
import com.dany.plo.model.RakModel;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;

/**
 *
 * @author Dany Candra
 */
public class PanelLokasiRak extends javax.swing.JPanel {

    private DynamicTableModel<RakModel> tableModel;
    private DynamicTableModel<DusModel> dusTableModel;

    private DusModel dusModel;
    private RakModel rakModel;
    private RakController rakController;

    /**
     * Creates new form PanelRak
     */
    public PanelLokasiRak() {
        rakModel = new RakModel();
        dusModel=new DusModel();
        rakController = new RakController();
        tableModel = new DynamicTableModel<>(RakModel.class);
        dusTableModel = new DynamicTableModel<>(DusModel.class);

        initComponents();

        tableRak.setDynamicModel(tableModel);
        tableDus.setDynamicModel(dusTableModel);
        rakController.setRakModel(rakModel);
        rakController.setDusModel(dusModel);
    }

    public DynamicTableModel<RakModel> getTableModel() {
        return tableModel;
    }

    public JDynamicTable getTableRak() {
        return tableRak;
    }

    public void reload() {
        rakController.reload(this);
    }

    public DynamicTableModel<DusModel> getDusTableModel() {
        return dusTableModel;
    }

    public JDynamicTable getTableDus() {
        return tableDus;
    }
    
    public void resetTable(){
        dusTableModel.clear();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSegarkan = new javax.swing.JButton();
        jPanelRak = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRak = new com.stripbandunk.jwidget.JDynamicTable();
        jPanelDus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDus = new com.stripbandunk.jwidget.JDynamicTable();

        buttonSegarkan.setText("SEGARKAN");
        buttonSegarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSegarkanActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSegarkan);

        jPanelRak.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daftar Rak"));

        tableRak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRak);

        javax.swing.GroupLayout jPanelRakLayout = new javax.swing.GroupLayout(jPanelRak);
        jPanelRak.setLayout(jPanelRakLayout);
        jPanelRakLayout.setHorizontalGroup(
            jPanelRakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelRakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelRakLayout.setVerticalGroup(
            jPanelRakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
            .addGroup(jPanelRakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanelDus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daftar Dus"));

        jScrollPane2.setViewportView(tableDus);

        javax.swing.GroupLayout jPanelDusLayout = new javax.swing.GroupLayout(jPanelDus);
        jPanelDus.setLayout(jPanelDusLayout);
        jPanelDusLayout.setHorizontalGroup(
            jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelDusLayout.setVerticalGroup(
            jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSegarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSegarkanActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_buttonSegarkanActionPerformed

    private void tableRakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRakMouseClicked
        // TODO add your handling code here:
        rakController.loadDus(this);
    }//GEN-LAST:event_tableRakMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSegarkan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDus;
    private javax.swing.JPanel jPanelRak;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.stripbandunk.jwidget.JDynamicTable tableDus;
    private com.stripbandunk.jwidget.JDynamicTable tableRak;
    // End of variables declaration//GEN-END:variables
}
