/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dany.plo.view;

import com.dany.plo.controller.DusController;
import com.dany.plo.model.DusModel;
import com.dany.plo.model.LantaiModel;
import com.dany.plo.view.resource.render.list.LokasiListCellRender;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.JPagination;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Dany Candra
 */
public class PanelLokasiDus extends javax.swing.JPanel {

    private DefaultComboBoxModel<LantaiModel> comboBoxModel;
    private DynamicTableModel<DusModel> tableModel;

    private DusController controller;
    private LantaiModel lantaiModel;
    private DusModel dusModel;

    private final int PAGE_SIZE = 20;

    /**
     * Creates new form PanelDusAuto
     */
    public PanelLokasiDus() {
        lantaiModel = new LantaiModel();
        dusModel = new DusModel();
        controller = new DusController();

        controller.setDusModel(dusModel);
        controller.setLantaiModel(lantaiModel);

        initComponents();

        tableModel = new DynamicTableModel<>(DusModel.class);
        tableDus.setDynamicModel(tableModel);

        comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxLokasi.setModel(comboBoxModel);
        comboBoxLokasi.setRenderer(new LokasiListCellRender());
        
      
    }

    public JButton getButtonTambah() {
        return buttonTambah;
    }

    public JComboBox getComboBoxLokasi() {
        return comboBoxLokasi;
    }

    public JPagination getjPagination() {
        return jPagination;
    }

    public JDynamicTable getTableDus() {
        return tableDus;
    }

    public JTextField getTextJumlahDus() {
        return textJumlahDus;
    }

    public DefaultComboBoxModel<LantaiModel> getComboBoxModel() {
        return comboBoxModel;
    }

    public DynamicTableModel<DusModel> getTableModel() {
        return tableModel;
    }

    public void initForm() {
        controller.loadComboBox(this);
        controller.reload(PAGE_SIZE, this);
        controller.cancel(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxLokasi = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        textJumlahDus = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDus = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination = new com.stripbandunk.jwidget.JPagination();

        jLabel1.setText("LOKASI");

        comboBoxLokasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("JUMLAH DUS");

        buttonTambah.setText("TAMBAHKAN");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        tableDus.setAutoCreateRowSorter(false);
        tableDus.setRowSorter(null);
        jScrollPane1.setViewportView(tableDus);

        jPagination.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPaginationOnPageChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxLokasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textJumlahDus)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonTambah))
                    .addComponent(jPagination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textJumlahDus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPaginationOnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPaginationOnPageChange
        // TODO add your handling code here:
        final int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        final int max = evt.getPageSize();
        controller.onPageChange(skip, max, this);
        controller.cancel(this);
    }//GEN-LAST:event_jPaginationOnPageChange

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        controller.insertAuto(this);
        initForm();
    }//GEN-LAST:event_buttonTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTambah;
    private javax.swing.JComboBox comboBoxLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.stripbandunk.jwidget.JPagination jPagination;
    private javax.swing.JScrollPane jScrollPane1;
    private com.stripbandunk.jwidget.JDynamicTable tableDus;
    private javax.swing.JTextField textJumlahDus;
    // End of variables declaration//GEN-END:variables
}
