/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.dany.plo.view.resource;

/**
 *
 * @author Dany Candra
 */
public class PanelCrud extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrud
     */
    public PanelCrud() {
        initComponents();
    }
    
    public void addCrudListener(CrudListener listener){
        listenerList.add(CrudListener.class, listener);
    }
    
    public void removeCrudListener(CrudListener listener){
        listenerList.remove(CrudListener.class, listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();

        buttonTambah.setText("TAMBAH");
        buttonTambah.setPreferredSize(new java.awt.Dimension(85, 23));
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        add(buttonTambah);

        buttonUbah.setText("UBAH");
        buttonUbah.setPreferredSize(new java.awt.Dimension(85, 23));
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        add(buttonUbah);

        buttonHapus.setText("HAPUS");
        buttonHapus.setPreferredSize(new java.awt.Dimension(85, 23));
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        add(buttonHapus);

        buttonBatal.setText("SEGARKAN");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });
        add(buttonBatal);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        CrudEvent event=new CrudEvent(this);
        CrudListener[] listeners = listenerList.getListeners(CrudListener.class);
        for (CrudListener crudListener : listeners) {
            crudListener.tambah(event);
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        CrudEvent event=new CrudEvent(this);
        CrudListener[] listeners = listenerList.getListeners(CrudListener.class);
        for (CrudListener crudListener : listeners) {
            crudListener.ubah(event);
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        CrudEvent event=new CrudEvent(this);
        CrudListener[] listeners = listenerList.getListeners(CrudListener.class);
        for (CrudListener crudListener : listeners) {
            crudListener.hapus(event);
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        CrudEvent event=new CrudEvent(this);
        CrudListener[] listeners = listenerList.getListeners(CrudListener.class);
        for (CrudListener crudListener : listeners) {
            crudListener.segarkan(event);
        }
    }//GEN-LAST:event_buttonBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    // End of variables declaration//GEN-END:variables
}
